main1:
	gcc -o main1 -I. array.c wave_simulation.c main1.c -lm

main2:
	gcc -o main2 -I. array.c wave_simulation.c main2.c -lm

main3:
	gcc -o main3 -I. array.c wave_simulation.c main3.c -lm

clean:
	rm -f main1
	rm -f main2
	rm -f main3
